version: "3"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8000:80
    depends_on:
      - api
      - ui
  api:
    build: ./app
    container_name: api
    ports:
      - 8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=cvd19
  ui:
    build: ./ui
    container_name: ui
    ports:
      - 80
    environment:
      - API_PROTOCOL=http
      - API_HOST=localhost
      - API_PORT=8000
  mongo:
    image: mongo:3.6.17
    container_name: mongo
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
  mongo-init:
    build: ./init/mongo-init
    container_name: mongo-init
    depends_on:
      - mongo
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=mongo
